# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/databases.json
Databases:
  pattern-demos-job:
    Url: jdbc:hsqldb:mem:pattern_demos_job
    Driver: org.hsqldb.jdbc.JDBCDriver
    Password: ${decrypt:}
